apiVersion: apps/v1
kind: Deployment
metadata:
  name: kasir-vnt-app  # Nama deployment
  labels:
    app: kasir-vnt    # Label yang digunakan untuk memilih pod
spec:
  replicas: 3  # Menjalankan 3 replika pod
  selector:
    matchLabels:
      app: kasir-vnt  # Memilih pod yang memiliki label ini
  template:
    metadata:
      labels:
        app: kasir-vnt  # Label yang akan digunakan oleh pod
    spec:
      containers:
      - name: kasir-vnt-app  # Nama container
        image: ${DOCKERHUB_CREDENTIALS_USR}/kasir_vnt_app:latest  # Docker image yang digunakan
        ports:
        - containerPort: 9000  # Port yang diteruskan ke luar
        env:
        - name: ENVIRONMENT
          value: "production"  # Menetapkan environment variables jika diperlukan
